#!/bin/bash
set -e

#app config
APP_NAME="tbootstrap"
APP_VERSION="1.0.0"
APP_AUTHOR="Tony NGUEREZA <nguerezatony@gmail.com>"
APP_BUILD_DATE="19/02/2017"
APP_WEB_SITE="http://www.nguereza-tony.cf"

echo
echo "Installing $APP_NAME ..."
echo

